<?php
require_once '../config/auth.php'; require_once '../config/database.php'; require_once '../config/content_points.php';
$rows=$pdo->query("SELECT c.*,s.name streamer_name,cs.name collab_name,(SELECT COUNT(*) FROM content_submission_images ci WHERE ci.submission_id=c.id) proof_count FROM content_submissions c JOIN streamers s ON s.id=c.streamer_id LEFT JOIN streamers cs ON cs.id=c.collab_streamer_id ORDER BY c.created_at DESC")->fetchAll();
$pending=array_filter($rows,fn($r)=>$r['status']==='pending');
function ctLabel($t){return ['vod'=>'VOD de Live','link_comum'=>'Link Comum','video_humor'=>'Vídeo Humorístico','video_novidades'=>'Vídeo de Novidades'][$t]??$t;}
function stLabel($s){return ['pending'=>'Pendente','approved'=>'Aprovado','rejected'=>'Recusado'][$s]??$s;}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conteúdos Enviados</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container"><a href="index.php">← Dashboard</a><div class="page-head"><div><p class="eyebrow">MODERAÇÃO</p><h1>Conteúdos Enviados</h1><p class="muted">Todo conteúdo precisa ser conferido antes de gerar pontos.</p></div><span class="badge pending"><?=count($pending)?> pendentes</span></div>
<div class="stats"><div class="stat"><small>PENDENTES</small><strong><?=count($pending)?></strong></div><div class="stat"><small>APROVADOS</small><strong><?=count(array_filter($rows,fn($r)=>$r['status']==='approved'))?></strong></div><div class="stat"><small>RECUSADOS</small><strong><?=count(array_filter($rows,fn($r)=>$r['status']==='rejected'))?></strong></div></div>
<table><thead><tr><th>Streamer</th><th>Tipo</th><th>Data</th><th>Collab/Raid</th><th>Status</th><th>Enviado</th><th>Comprovantes</th><th>Ação</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=htmlspecialchars($r['streamer_name'])?></strong></td><td><?=ctLabel($r['content_type'])?></td><td><?=date('d/m/Y',strtotime($r['submission_date']))?></td><td><?=$r['collab']?'Sim'.($r['collab_name']?' · '.htmlspecialchars($r['collab_name']):''):'Não'?></td><td><span class="status <?=htmlspecialchars($r['status'])?>"><?=stLabel($r['status'])?></span></td><td><?=date('d/m/Y H:i',strtotime($r['created_at']))?></td><td><?=((int)$r['proof_count']>0?'📸 '.(int)$r['proof_count']:'—')?></td><td><a class="btn small-btn primary" href="submissao.php?id=<?=$r['id']?>"><?= $r['status']==='pending'?'Analisar':'Ver' ?></a></td></tr><?php endforeach;?></tbody></table>
</main><footer class="site-footer">Morningfall Creators V1 <span>•</span> Desenvolvido por <a href="https://discord.com/users/207712204890439680" target="_blank" rel="noopener noreferrer">luciferms666</a></footer></body></html>