<?php
require_once '../config/auth.php';require_once '../config/database.php';require_once '../config/vod_points.php';
ensureVodPointsMigrated($pdo, (int)$_SESSION['staff_id']);
$rows=$pdo->query("SELECT v.*,s.name streamer_name FROM vods v JOIN streamers s ON s.id=v.streamer_id ORDER BY v.created_at DESC")->fetchAll();
function formatDurationHM(int $minutes): string { return sprintf('%02d:%02d', intdiv($minutes,60), $minutes%60); }
$totalMinutes=0; foreach($rows as $x){$totalMinutes+=(int)$x['duration_minutes'];}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VODs</title><link rel="stylesheet" href="../assets/css/style.css"></head><body><main class="container"><a href="index.php">← Dashboard</a><div class="page-head"><h1>VODs</h1><a class="btn primary" href="vod_nova.php">+ Cadastrar VOD</a></div>
<div class="stats"><div class="stat"><span>VODs registradas</span><strong><?=count($rows)?></strong></div><div class="stat"><span>Tempo total</span><strong><?=formatDurationHM($totalMinutes)?></strong></div></div>
<table><thead><tr><th>Streamer</th><th>Data</th><th>VOD</th><th>Duração</th><th>Pontos</th><th>Ações</th></tr></thead><tbody><?php foreach($rows as $x): ?><tr><td><?=htmlspecialchars($x['streamer_name'])?></td><td><?=$x['vod_date']?></td><td><a href="<?=htmlspecialchars($x['url'])?>" target="_blank">Abrir</a></td><td><?=formatDurationHM((int)$x['duration_minutes'])?></td><td>+<?=$x['points_awarded']?></td><td><a class="btn danger-btn" href="../api/delete_vod.php?id=<?=$x['id']?>" onclick="return confirm('Excluir esta VOD? A pontuação do dia será recalculada automaticamente.')">Excluir</a></td></tr><?php endforeach;?></tbody></table><p class="muted">A duração é exibida em <strong>HH:MM</strong>. A pontuação soma as VODs do mesmo streamer na mesma data: 1 ponto por hora completa, até 10 pontos por dia.</p></main><footer class="site-footer">Morningfall Creators V1 <span>•</span> Desenvolvido por <a href="https://discord.com/users/207712204890439680" target="_blank" rel="noopener noreferrer">luciferms666</a></footer></body></html>
